### ISSUE TITLE
Add copyright notice to license

### ISSUE THREAD

**Issue by ghost** [fauna-brecht/hello-world-gatsby-faunadb#1]
This is a great starter but as it stands the work added to the `gatsby-starter` is unclear from a licensing perspective given no copyright notice was added by the author. Please add a copyright notice. For more information see: https://writing.kemitchell.com/2016/09/21/MIT-License-Line-by-Line.html. If you're unsure how to add a notice let me know and I'll help.

Related: https://github.com/gatsbyjs/gatsby/issues/25091

**Comment by fauna-brecht** [comment]
I am indeed unsure how to add this and have to say, I'm not the original author (it was written for FaunaDB by a blog-writing contractor) of the code although I cleaned it up slightly. I'm happy to take your advice on how I should add a copyright notice and will apply your advice on future starter repositories like this. 

I assume I should add:
Copyright for portions of hello-world-gatsby-faunadb are held by gatsbyjs, 2015 as 
part of project gatsby-starter-default. 
All other copyright for project hello-world-gatsby-faunadb are held by FaunaDB, 2020.

Is that correct?

**Comment by balibebas** [comment]
Hello, Sir. As far as I know all you need is the copyright line added with your name/pseudonym so it's clear any modifications you made you intend to be free and clear of any copyright claims, and to also make it clear which specific license those changes are under (read: because they could be GPL on top of an MIT license, for example). The others I've spotted and linked to the upstream Gatsby issue did do as you suggest but as far as I'm aware that's not a requirement of the MIT license.

**Comment by ghost** [comment]
Gatsby just moved the starters over to 0BSD so you can simply `s/gatsbyjs/yourname` in the LICENSE and call it a day if you plan to release your source under the MIT license.

**Comment by fauna-brecht** [comment]
Moved it to 0BSD which should be fine as well and less restrictive for users who want to experiment with the code if I'm not mistaking. Of course with s/gatsbyjs/yourname applied.

**Comment by balibebas** [comment]
That's fantastic and very thoughtful for your users. Hope to see more starters with Auth like this one because it's a way better experience than Auth0 IMO. Cheers.
